[package]
name = "lab1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "node"
path = "src/node.rs"

[[bin]]
name = "hub"
path = "src/hub.rs"

